# Generated by Django 5.2.10 on 2026-01-12 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(db_index=True, max_length=100)),
                ('role', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('required_skills', models.JSONField()),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('stipend', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('skills', models.JSONField()),
                ('interests', models.JSONField(blank=True, null=True)),
                ('projects', models.JSONField(blank=True, null=True)),
                ('experience_summary', models.TextField(blank=True, null=True)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('resume_text', models.TextField(blank=True, help_text='Paste resume content or LaTeX code', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('match_summary', models.TextField()),
                ('skill_gaps', models.JSONField()),
                ('generated_resume', models.TextField()),
                ('recommendation_text', models.TextField()),
                ('ats_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentAnalytics.internship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentAnalytics.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'internship', 'version')},
            },
        ),
    ]
